apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: krtk
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: krtk
    newName: rg.fr-par.scw.cloud/djnd/krtk
    newTag: '0fb5609fafd1df9e0f2815e441bd56487d18212a'
