apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: krtk
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: krtk
    newName: rg.fr-par.scw.cloud/djnd/krtk
    newTag: 'f99a5d740db24d183eb2fadfd21a090ec4038f4d'
