apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: krtk
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: krtk
    newName: rg.fr-par.scw.cloud/djnd/krtk
    newTag: '1636b392c35f0d225ef63b7858604b85a96a0e3b'
