apiVersion: v1
kind: Secret
metadata:
  name: krtk-secrets
type: Opaque
stringData:
  FLASK_DATABASE_HOST: db
  FLASK_DATABASE_NAME: flask
  FLASK_DATABASE_USERNAME: flask
  FLASK_DATABASE_PASSWORD: changeme
