"""Initial migration

Revision ID: 1a161105f005
Revises: 
Create Date: 2023-12-26 13:46:53.603601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a161105f005"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shortened_link",
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("destination", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("alias"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shortened_link")
    # ### end Alembic commands ###
